name: ASP.NET Core CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish application
      run: dotnet publish -c Release -o publish

    - name: Upload publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-publish-output
        path: publish
  
  # =========================
  # CD JOB (Deploy)
  # =========================
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: app-publish-output
        path: deploy-folder

    - name: Deploy to IIS
      run: |
        if(!(Test-Path "C:\inetpub\wwwroot\MyApp")) {
	   New Item -ItemType Directory -path "C:\inetpub\wwwroot\MyApp"
	}
	Copy Item -path "deploy-folder\*" -Destination "C:\inetpub\wwwroot\MyApp" -Recurse -Force
